### ISSUE TITLE
0.3.0 Runtime errors

### ISSUE THREAD

**Issue by sgwilym** [rmosolgo/graphql-relay-ruby#4]
Creating a completely new rails app, adding `graphql-relay` to the gemfile, installing the gems and then trying to boot the app gets me this error:

```
/Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-relay-0.3.0/lib/graphql/definition_helpers/defined_by_config/definition_config.rb:32:in `<class:DefinitionConfig>': undefined method `field' for class `GraphQL::DefinitionHelpers::DefinedByConfig::DefinitionConfig' (NameError)
	from /Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-relay-0.3.0/lib/graphql/definition_helpers/defined_by_config/definition_config.rb:4:in `<module:DefinedByConfig>'
	from /Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-relay-0.3.0/lib/graphql/definition_helpers/defined_by_config/definition_config.rb:3:in `<module:DefinitionHelpers>'
	from /Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-relay-0.3.0/lib/graphql/definition_helpers/defined_by_config/definition_config.rb:2:in `<module:GraphQL>'
	from /Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-relay-0.3.0/lib/graphql/definition_helpers/defined_by_config/definition_config.rb:1:in `<top (required)>'

```

**Comment by rmosolgo** [comment]
Oops! `graphql-relay` wasn't requiring its `graphql` dependency, but it the `spec_helper` _did_ require it, so this didn't appear in tests.

Here's the fix:

https://github.com/rmosolgo/graphql-relay-ruby/commit/d9526f477540bee80b3702b0c11fad092e187671

Also pushed to 0.3.1 on rubygems
